apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: hawtio-kubernetes-api
  labels:
    app: hawtio-kubernetes-api
spec:
  type: NodePort
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 80
  selector:
    app: hawtio-kubernetes-api
