apiVersion: v1
kind: Service
metadata:
  name: hawtio-kubernetes-api
  labels:
    app: hawtio-online
spec:
  type: NodePort
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 80
  selector:
    app: hawtio-online
